{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "envoy-edge.serviceAccountName" . }}
  labels:
    {{- include "envoy-edge.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.ServiceAccountToken.enabled }}
automountServiceAccountToken: {{ .Values.serviceAccount.ServiceAccountToken.automountServiceAccountToken }}
{{- end }}

